edited few items

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,30 +10,36 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      # Checkout source code
       - name: Checkout Repository
         uses: actions/checkout@v4
 
+      # Setup Java
       - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
           distribution: temurin
           java-version: '17'
 
+      # Give Gradle permission
       - name: Grant execute permission
         run: chmod +x gradlew
 
+      # Build project
       - name: Build Project
         run: ./gradlew clean build -x test
 
+      # Copy only the jar to EC2
       - name: Copy JAR to EC2
         uses: appleboy/scp-action@v0.1.7
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.EC2_SSH_KEY }}
-          source: "build/libs/*.jar"
+          source: "build/libs/demo-0.0.1-SNAPSHOT.jar"
           target: "/opt/cicd"
 
+      # Restart application
       - name: Restart Application
         uses: appleboy/ssh-action@v1.0.3
         with:
@@ -42,9 +48,37 @@ jobs:
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
             cd /opt/cicd
-            pkill -f demo-0.0.1-SNAPSHOT.jar || true
-            sleep 2
-            setsid nohup java -jar demo-0.0.1-SNAPSHOT.jar > app.log 2>&1 < /dev/null &
-            disown
-            sleep 5
-            ps -ef | grep demo-0.0.1-SNAPSHOT.jar || true
+
+            echo "Current Directory:"
+            pwd
+
+            echo "Files:"
+            ls -lh
+
+            PID=$(pgrep -f "demo-0.0.1-SNAPSHOT.jar")
+
+            if [ ! -z "$PID" ]; then
+              echo "Stopping existing application (PID=$PID)"
+              kill -15 $PID
+              sleep 5
+            else
+              echo "No existing application found."
+            fi
+
+            echo "Starting application..."
+            nohup java -jar demo-0.0.1-SNAPSHOT.jar > app.log 2>&1 < /dev/null &
+
+            sleep 10
+
+            PID=$(pgrep -f "demo-0.0.1-SNAPSHOT.jar")
+
+            if [ ! -z "$PID" ]; then
+              echo "Application started successfully."
+              echo "Running PID: $PID"
+              exit 0
+            else
+              echo "Application failed to start."
+              echo "========== APP LOG =========="
+              cat app.log
+              exit 1
+            fi
